theme: minima

title: "Qian's Blog"
author: "Qian Zhong"
email: blog@chadbaldwin.net
url: https://qzhongmun.github.io/

timezone: UTC # GitHub uses UTC. This is to force dev environment to match
future: false # GitHub Pages will publish future posts if this isn't set to false

description: "Front-end Developer & Testing Engineer" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

rss: rss

show_excerpts: false

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "qzhong@mun.ca"
twitter_username: "Eva"
github_username: "qzhongmun"
linkedin_username: "QIAN ZHONG"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

social-links:
  Resume:        https://chadbaldwin.net/resume
  LinkedIn:      https://www.linkedin.com/in/qian-zhong-a5880422a
  GitHub:        https://github.com/qzhongmun
  Website:       https://qzhongmun.github.io/

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################


kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - resume.html
  - archive.html


google_analytics: UA-185058308-1
gravatar_hash: 2136e716a089f4a3794f4007328c7bfb
code_block_max_height: 500px

home_post_limit: 5

# The github repo that is to be used for looking up comments
comments_repo: qzhongmun/qzhongmun.github.io

defaults:
  - scope:
      path: ""
    values:
      image: https://s.gravatar.com/avatar/2136e716a089f4a3794f4007328c7bfb?s=800 # Apply default site image
  - scope:
      path: ""
      type: posts
    values:
      tags: Other # Add a default tag to all posts
